name: "Create release"

on: "push"
#  push:
#    tags:
#      - '*'

jobs:
  build:
    strategy:
      matrix:
        program:
          - cryptomizer
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        include:
          - os: windows-latest
            name: windows
          - os: ubuntu-latest
            name: linux
          - os: macos-latest
            name: macos
    name: ${{ matrix.program }}-${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install MSYS2 Dependencies
        if: matrix.platform.name == windows
        uses: msys2/setup-msys2@v2
        with:
          install: make
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install Python Dependencies
        run: |
          pip install pipenv
          pipenv install
      - uses: actions/checkout@v3
      - name: Build
        run: |
          pipenv shell
          make build-${{ matrix.name }}
      - name: Zip Artifact
        uses: thedoctor0/zip-release@master
        with:
          filename: ${{ matrix.program }}-${{ matrix.name }}.zip
          path: ./dist/*
      - name: Upload Artifact
        with:
          name: ${{ matrix.program }}-${{ matrix.name }}
          path: ${{ matrix.program }}-${{ matrix.name }}.zip
      - name: Release Artifact
        uses: Xotl/cool-github-releases@v1
        with:
          mode: update
          tag_name: ci
          release_name: Automatic Builds
          assets: ${{ matrix.program }}-${{ matrix.name }}.zip
          github_token: ${{ secrets.GITHUB_TOKEN }}
          replace_assets: true
          body_mrkdwn: |
            _Corresponding commit: ${{ github.sha }}_
