name: "Create release"

on: "push"
#  push:
#    tags:
#      - '*'

jobs:
  build_linux:
    runs-on: ubuntu-22.04
    name: Create linux package
    strategy:
      matrix:
        python-version: ["3.10.0"]
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: ${{matrix.python-version}}
      - name: "Install dependencies"
        run: |
          sudo apt install make
          python -VV
          python -m pip install pipenv
          python -m pipenv install
      - name: "Build package"
        run: |
          make build-linux
      - uses: "actions/upload-artifact@v3"
        with:
          name: "build-linux-artifact"
          path: "dist"
          

#  build_windows:
#    runs-on: windows-2022
#    name: Create windows package